apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ include "task-platform.namespace" . }}
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ include "task-platform.namespace" . }}
data:
  DB_HOST: "postgres.{{ .Values.namespace }}.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  PORT: "3000"
