apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ include "task-platform.namespace" . }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef: { name: postgres-config }
            - secretRef: { name: postgres-secret }
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          readinessProbe:
            exec: { command: ["pg_isready", "-U", "{{ .Values.database.user }}"] }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec: { command: ["pg_isready", "-U", "{{ .Values.database.user }}"] }
            initialDelaySeconds: 15
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "task-platform.namespace" . }}
spec:
  selector: { app: postgres }
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
